import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import { convertDuration } from '../../helpers/time';
import { SessionHistory } from '../../Types'

const getSessionHistory = async (sessionUID: string) => {
    return await fetch(`http://localhost:3000/api/laps/${sessionUID}`).then(res => res.json()) as SessionHistory
}

const Lap: NextPage = () => {
    const router = useRouter()
    const { sessionUID } = router.query
    const [sessionHistory, setSessionHistory] = useState<SessionHistory>()

    useEffect(() => {
        async function _getSessions() {
            if (!sessionUID) {
                return
            }

            const sessionHistory = await getSessionHistory(sessionUID as string)

            setSessionHistory(sessionHistory)
        }

        _getSessions()
    }, [sessionUID])

    return (
        <div>
            <Head>
                <title>F1 Telemetry</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='w-1/2 h-screen font-mono border'>
                <h1 className='text-4xl text-center '>LAPS</h1>

                <table className='w-full mt-10'>
                    <thead>
                        <tr>
                            <th className='border'>Lap</th>
                            <th className='border'>Pos</th>
                            <th className='border'>Tyre</th>
                            <th className='border'>Lap Time</th>
                            <th className='border' colSpan={3}>Sector Times</th>
                        </tr>
                    </thead>

                    <tbody>
                        {sessionHistory?.m_lapHistoryData.map((lap, idx) => (
                            <tr key={idx} className='cursor-pointer hover:bg-gray-100'>
                                <td className='text-center border'>{idx + 1}</td>
                                <td className='text-center border'>{lap.m_lapTimeInMS}</td>
                                <td className='text-center border'>{lap.m_lapTimeInMS}</td>
                                <td className='text-center border'>{convertDuration(lap.m_lapTimeInMS)}</td>
                                <td className='text-center border'>{convertDuration(lap.m_sector1TimeInMS)}</td>
                                <td className='text-center border'>{convertDuration(lap.m_sector2TimeInMS)}</td>
                                <td className='text-center border'>{convertDuration(lap.m_sector3TimeInMS)}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    )
}

export default Lap
