// Generated by https://quicktype.io

export interface Session {
    _id:                         string;
    m_header:                    MHeader;
    m_weather:                   number;
    m_trackTemperature:          number;
    m_airTemperature:            number;
    m_totalLaps:                 number;
    m_trackLength:               number;
    m_sessionType:               number;
    m_trackId:                   number;
    m_era:                       null;
    m_formula:                   number;
    m_sessionTimeLeft:           number;
    m_sessionDuration:           number;
    m_pitSpeedLimit:             number;
    m_gamePaused:                number;
    m_isSpectating:              number;
    m_spectatorCarIndex:         number;
    m_sliProNativeSupport:       number;
    m_numMarshalZones:           number;
    m_marshalZones:              MMarshalZone[];
    m_safetyCarStatus:           number;
    m_networkGame:               number;
    m_numWeatherForecastSamples: number;
    m_weatherForecastSamples:    MWeatherForecastSample[];
    createdAt:                   string;
    sessionHistory:              SessionHistory;
    participants:                Participant;
}

export interface MHeader {
    m_packetFormat:            number;
    m_gameMajorVersion:        number;
    m_gameMinorVersion:        number;
    m_packetVersion:           number;
    m_packetId:                number;
    m_sessionUID:              string;
    m_sessionTime:             number;
    m_frameIdentifier:         number;
    m_playerCarIndex:          number;
    m_secondaryPlayerCarIndex: number;
}

export interface MMarshalZone {
    m_zoneStart: number;
    m_zoneFlag:  number;
}

export interface MWeatherForecastSample {
    m_sessionType:            number;
    m_timeOffset:             number;
    m_weather:                number;
    m_trackTemperature:       number;
    m_trackTemperatureChange: number;
    m_airTemperature:         number;
    m_airTemperatureChange:   number;
    m_rainPercentage:         number;
}

export interface SessionHistory {
    _id:                     string;
    m_header:                MHeader;
    m_carIdx:                number;
    m_numLaps:               number;
    m_numTyreStints:         number;
    m_bestLapTimeLapNum:     number;
    m_bestSector1LapNum:     number;
    m_bestSector2LapNum:     number;
    m_bestSector3LapNum:     number;
    m_lapHistoryData:        MLapHistoryDatum[];
    m_tyreStintsHistoryData: MTyreStintsHistoryDatum[];
    createdAt:               string;
}

export interface MLapHistoryDatum {
    m_lapTimeInMS:      number;
    m_sector1TimeInMS:  number;
    m_sector2TimeInMS:  number;
    m_sector3TimeInMS:  number;
    m_lapValidBitFlags: number;
}

export interface MTyreStintsHistoryDatum {
    m_endLap:             number;
    m_tyreActualCompound: number;
    m_tyreVisualCompound: number;
}

export interface Participant {
    _id:            string;
    m_header:       MHeader;
    m_numCars:      null;
    m_participants: MParticipant[];
    createdAt:      string;
}

export interface MParticipant {
    m_aiControlled:  number;
    m_driverId:      number;
    m_networkId:     number;
    m_teamId:        number;
    m_myTeam:        number;
    m_raceNumber:    number;
    m_nationality:   number;
    m_name:          string;
    m_yourTelemetry: number;
}
