import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { DRIVERS } from '../constants/drivers'
import { SESSION_TYPES } from '../constants/sessionTypes'
import { TEAMS } from '../constants/teams'
import { TRACKS } from '../constants/track'
import { convertDuration } from '../helpers/time'
import { Driver, ISessionDoc, LapHistoryData, Team } from '../Types'

interface ParsedSession {
    sessionUID: string;
    type: string;
    track: string;
    driver: Driver;
    team: Team;
    totalLap: number
    bestLapTime: string;
    bestSector1Time: string;
    bestSector2Time: string;
    bestSector3Time: string;
    date: Date;
}

const getSessions = async () => {
    return await fetch('http://localhost:3000/api/sessions').then(res => res.json()) as ISessionDoc[]
}

const getBestTime = (m_lapHistoryData: LapHistoryData[], key: keyof LapHistoryData) => {
    const sorted = m_lapHistoryData.sort((a, b) => {
        if (a[key] < b[key]) {
            return -1;
        }

        if (a[key] > b[key]) {
            return 1;
        }
        
        return 0;
    })

    return sorted[0]
}

const Home: NextPage = () => {
    const [sessions, setSessions] = useState<ParsedSession[]>([])
    useEffect(() => {
        async function _getSessions() {
            const sessions = await getSessions()
            const parsedSessions = sessions.map(session => {
                const bestLapTimeData = getBestTime(session.sessionHistory?.m_lapHistoryData, 'm_lapTimeInMS')
                const bestSector1TimeData = getBestTime(session.sessionHistory?.m_lapHistoryData, 'm_sector1TimeInMS')
                const bestSector2TimeData = getBestTime(session.sessionHistory?.m_lapHistoryData, 'm_sector2TimeInMS')
                const bestSector3TimeData = getBestTime(session.sessionHistory?.m_lapHistoryData, 'm_sector3TimeInMS')
                const player = session.participants.find(participant => participant.carIndex === session.m_playerCarIndex)
                let team = { name: 'N/A', color: 'N/A' }
                let driver = { abbreviation: 'SAI', firstName: 'Carlos', lastName: 'Sainz' }

                if (player) {
                    driver = DRIVERS[player.m_driverId] || { abbreviation: player.m_name, firstName: player.m_name, lastName: player.m_name }
                    team = TEAMS[player.m_teamId] || team
                }

                return {
                    sessionUID: session.m_sessionUID,
                    track: TRACKS[session.m_trackId].name,
                    team: team,
                    driver: driver,
                    type: SESSION_TYPES[session.m_sessionType].long,
                    totalLap: session.m_totalLaps,
                    bestLapTime: convertDuration(bestLapTimeData ? bestLapTimeData.m_lapTimeInMS : 0),
                    bestSector1Time: convertDuration(bestSector1TimeData ? bestSector1TimeData.m_sector1TimeInMS : 0),
                    bestSector2Time: convertDuration(bestSector2TimeData ? bestSector2TimeData.m_sector2TimeInMS : 0),
                    bestSector3Time: convertDuration(bestSector3TimeData ? bestSector3TimeData.m_sector3TimeInMS : 0),
                    date: new Date((new Date(session.createdAt)).getTime() - session.m_sessionTime)
                }
            })

            setSessions(parsedSessions)
        }

        _getSessions()
    }, [])

    return (
        <div>
            <Head>
                <title>F1 Telemetry</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='w-1/2 h-screen mx-auto font-mono'>
                <h1 className='text-4xl text-center '>SESSIONS</h1>

                <table className='w-full mt-10'>
                    <thead>
                        <tr>
                            <th className='p-2 border border-b-0'>Track</th>
                            <th className='p-2 border border-b-0'>Driver</th>
                            <th className='p-2 border border-b-0'>Car</th>
                            <th className='p-2 border border-b-0'>Type</th>
                            <th className='p-2 border border-b-0'>Laps</th>
                            <th className='p-2 border border-b-0'>Best Lap</th>
                            <th className='p-2 border border-b-0' colSpan={3}>Best Sectors</th>
                            <th className='p-2 border border-b-0'>Date</th>
                        </tr>
                    </thead>

                    <tbody>
                        {sessions.map(session => (
                            <Link key={session.sessionUID} href={`/laps/${session.sessionUID}`}>
                                <tr className='cursor-pointer hover:bg-blue-100 odd:bg-gray-100' >
                                    <td className='p-2 border' style={{ borderColor: session.team.color }}>{session.track}</td>
                                    <td className='p-2 border' style={{ borderColor: session.team.color }}>{session.driver.firstName} {session.driver.lastName}</td>
                                    <td className='p-2 border' style={{ borderColor: session.team.color, color: session.team.color }}>{session.team.name}</td>
                                    <td className='p-2 border' style={{ borderColor: session.team.color }}>{session.type}</td>
                                    <td className='p-2 text-center border' style={{ borderColor: session.team.color }}>{session.totalLap}</td>
                                    <td className='p-2 text-center border' style={{ borderColor: session.team.color }}>{session.bestLapTime}</td>
                                    <td className='p-2 text-center border' style={{ borderColor: session.team.color }}>{session.bestSector1Time}</td>
                                    <td className='p-2 text-center border' style={{ borderColor: session.team.color }}>{session.bestSector2Time}</td>
                                    <td className='p-2 text-center border' style={{ borderColor: session.team.color }}>{session.bestSector3Time}</td>
                                    <td className='p-2 text-center border' style={{ borderColor: session.team.color }} width={'22%'}>{session.date.toLocaleString('en-CA')}</td>
                                </tr>
                            </Link>
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    )
}

export default Home
