export const TYRES = [
    { color: '#ffb3c3', name: 'Hyper Soft' },
    { color: '#b14ba7', name: 'Ultra Soft' },
    { color: '#f92d29', name: 'Super Soft' },
    { color: '#ebd25f', name: 'Soft' },
    { color: '#ffffff', name: 'Medium' },
    { color: '#03a2f3', name: 'Hard' },
    { color: '#ff803f', name: 'Super Hard' },
    { color: '#3ac82b', name: 'Intermediate' },
    { color: '#4491d2', name: 'Wet' },
    { color: '#3ac82b', name: 'Dry' },
    { color: '#4491d2', name: 'Wet' },
    { color: '#f92d29', name: 'Super Soft' },
    { color: '#f92d29', name: 'Soft' },
    { color: '#ebd25f', name: 'Medium' },
    { color: '#ffffff', name: 'Hard' },
    { color: '#4491d2', name: 'Wet' },
    { color: '#f92d29', name: 'C5' },
    { color: '#f92d29', name: 'C4' },
    { color: '#ebd25f', name: 'C3' },
    { color: '#ffffff', name: 'C2' },
    { color: '#ffffff', name: 'C1' },
]
